# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev_Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_detail', models.CharField(max_length=30, unique=True, verbose_name='脚本功能')),
                ('script_type', models.CharField(max_length=10, verbose_name='脚本类型')),
                ('env', models.CharField(choices=[('生产', '生产'), ('预发', '预发'), ('测试', '测试'), ('开发中', '开发中')], max_length=20, verbose_name='脚本执行环境')),
                ('script_dir', models.CharField(blank=True, max_length=100, verbose_name='脚本目录')),
                ('cmd_template', models.CharField(blank=True, max_length=100, verbose_name='命令模板')),
                ('parameter_num', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, max_length=2, verbose_name='参数个数')),
                ('editor', models.TextField(verbose_name='备注')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
