# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dev_script',
            options={'verbose_name': '自动化脚本', 'verbose_name_plural': '自动化脚本'},
        ),
    ]
