# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_auto_20171126_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_script',
            name='script_type',
            field=models.CharField(choices=[('python', 'python'), ('sell', 'sell'), ('fabric', 'fabric'), ('ansible', 'ansible')], max_length=10, verbose_name='脚本类型'),
        ),
    ]
