# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_auto_20171126_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev_script',
            name='script_dir',
            field=models.CharField(blank=True, max_length=100, verbose_name='脚本路径'),
        ),
    ]
