# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Install_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(choices=[(0, '惠普'), (1, '戴尔')], max_length=10, verbose_name='服务器类型')),
                ('os', models.CharField(choices=[(0, 'Centos6'), (1, 'Centos7')], default=1, max_length=10, verbose_name='操作系统')),
                ('sn_number', models.CharField(max_length=50, unique=True, verbose_name='SN号')),
                ('server_cabinet', models.CharField(max_length=20, verbose_name='服务器机柜')),
                ('location', models.IntegerField(verbose_name='起始位置')),
                ('ilo_ip', models.GenericIPAddressField(unique=True, verbose_name='管理IP')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('dns', models.GenericIPAddressField(verbose_name='DNS')),
                ('gateway', models.GenericIPAddressField(verbose_name='网关')),
                ('mac_addr', models.CharField(max_length=50, verbose_name='网卡')),
                ('addr_type', models.CharField(max_length=50, verbose_name='配置类型')),
            ],
        ),
    ]
