# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0002_install_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install_list',
            name='os',
            field=models.CharField(choices=[(0, 'Centos6'), (1, 'Centos7')], max_length=10, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='install_list',
            name='status',
            field=models.CharField(choices=[(0, '未安装'), (1, '已安装')], max_length=5, verbose_name='安装状态'),
        ),
    ]
