# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('install', '0003_auto_20170923_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install_list',
            name='os',
            field=models.IntegerField(choices=[(0, 'Centos6'), (1, 'Centos7')], default=1, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='install_list',
            name='server_type',
            field=models.IntegerField(choices=[(0, '惠普'), (1, '戴尔')], verbose_name='服务器类型'),
        ),
        migrations.AlterField(
            model_name='install_list',
            name='status',
            field=models.IntegerField(choices=[(0, '未安装'), (1, '已安装')], default=0, verbose_name='安装状态'),
        ),
    ]
