# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP地址')),
                ('host_name', models.CharField(blank=True, max_length=100, verbose_name='主机名')),
                ('host_type', models.CharField(choices=[('物理机', '物理机'), ('虚拟机', '虚拟机'), ('云主机', '云主机')], default='虚拟机', max_length=10, verbose_name='主机类型')),
                ('cpu', models.CharField(blank=True, max_length=10, verbose_name='CPU')),
                ('memery', models.CharField(blank=True, max_length=10, verbose_name='内存')),
                ('hard_disk', models.CharField(blank=True, max_length=40, verbose_name='硬盘')),
                ('system_type', models.CharField(choices=[('Centos', 'Centos'), ('Windows', 'Windows')], max_length=20, verbose_name='操作系统')),
                ('environment', models.CharField(choices=[('开发', '开发'), ('测试', '测试'), ('预发', '预发'), ('生产', '生产')], max_length=10, verbose_name='环境')),
                ('eth_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, verbose_name='网口数')),
                ('idle', models.CharField(choices=[('使用中', '使用中'), ('空闲', '空闲')], default='使用中', max_length=10, verbose_name='使用状态')),
                ('cost', models.IntegerField(blank=True)),
                ('editor', models.TextField(blank=True, verbose_name='备注')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('physical_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Host', verbose_name='父主机')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='assets.Project', verbose_name='项目'),
        ),
    ]
