# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.CharField(blank=True, default='未使用', max_length=50, verbose_name='项目名'),
        ),
    ]
