# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import select2.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_project_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='host',
            name='physical_host',
            field=select2.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Host', verbose_name='虚拟机父主机'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project',
            field=select2.fields.ManyToManyField(blank=True, null=True, sorted=False, to='assets.Project', verbose_name='项目'),
        ),
    ]
