# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20171110_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cost',
            field=models.IntegerField(blank=True, default=0, verbose_name='价格'),
        ),
    ]
