# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20171110_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chinese_detail',
            field=models.CharField(default=2, max_length=20, verbose_name='中文描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, choices=[('开发', '开发'), ('运维', '运维'), ('架构', '架构')], max_length=10, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='project',
            name='env',
            field=models.CharField(choices=[('开发', '开发'), ('测试', '测试'), ('预发', '预发'), ('生产', '生产')], default=2, max_length=30, verbose_name='环境'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='master',
            field=models.CharField(blank=True, max_length=30, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(default='未使用', max_length=50, verbose_name='项目名'),
        ),
    ]
