# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20171116_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
    ]
