# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20171123_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_addr',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project',
            field=models.CharField(max_length=50, unique=True, verbose_name='项目名'),
        ),
    ]
