# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20171127_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='physical_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Host', verbose_name='虚拟机父主机'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project',
            field=models.ManyToManyField(blank=True, to='assets.Project', verbose_name='项目'),
        ),
    ]
